apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook-warehouse
  namespace: kargo-advanced
spec:
  freightCreationPolicy: Manual
  subscriptions:
  - chart:
      repoURL: ghcr.io/csz-akuity/guestbook
      imageSelectionStrategy: SemVer
      constraint: ">=0.1.1762403815-0"
      # allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  # - image:
      # repoURL: docker.io/cszakuity/csz-private-repo
      # imageSelectionStrategy: Lexical
      # imageSelectionStrategy: Digest
      # constraint: latest
      # allowTags: ^release-.*$
      # strictSemvers: false
  - git:
      repoURL: https://github.com/csz-ghorg/kargo-advanced.git
      branch: main
