apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook-warehouse
  namespace: kargo-advanced
spec:
  freightCreationPolicy: Manual
  interval: 24h0m0s
  subscriptions:
  - image:
      repoURL: ghcr.io/csz-akuity/guestbook
      imageSelectionStrategy: SemVer
      # No constraint - tracks latest version
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  - image:
      repoURL: docker.io/cszakuity/csz-private-repo
      imageSelectionStrategy: Lexical
      # imageSelectionStrategy: Digest
      # constraint: latest
      allowTags: ^release-.*$
      # strictSemvers: false
  - git:
      repoURL: https://github.com/csz-ghorg/kargo-advanced.git
      branch: main
